workflows:
  version: 2
  node-multi-build:
    jobs:
      - build
      - build-10

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-{{ .Environment.CIRCLE_STAGE }}-dependencies-{{ checksum "package.json" }}
          - v1-{{ .Environment.CIRCLE_STAGE }}-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn test
    working_directory: ~/repo

  build:
    <<: *node-base
    docker:
      - image: circleci/node:8
  build-10:
    <<: *node-base
    docker:
      - image: circleci/node:10
